acme_admin_homepage:
    pattern:  /admin/
    defaults: { _controller: AcmeAdminBundle:Default:index }

admin_login:
    pattern: /login
    defaults: { _controller: AcmeAdminBundle:Security:login }

admin_login_check:
    pattern: /login_check
    defaults: { _controller: AcmeAdminBundle:Security:login_check }

disabled_endpoint:
    pattern: /disabled/{id}
    defaults: { _controller: AcmeAdminBundle:Default:disabledEndpoint }
