<?php

namespace Acme\WeatherBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EndpointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodeWeatherRepository extends EntityRepository
{
    public function getCodeDescription($code){
        return $this->getEntityManager()
            ->createQuery('SELECT cw.description  FROM AcmeWeatherBundle:CodeWeather cw WHERE cw.code = ' . $code)
            ->getResult();
    }
}
