<?php

namespace Acme\WeatherBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EndpointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EndpointRepository extends EntityRepository
{
    public function getAllEndpoins(){
        return $this->getEntityManager()
            ->createQuery('SELECT e.endpoint, e.parser FROM AcmeWeatherBundle:Endpoint e WHERE e.enabled = 1')
            ->getResult();
    }

    public function getEndpoins(){
        return $this->getEntityManager()
            ->createQuery('SELECT e.id, e.endpoint, e.parser, e.enabled, e.serviceName FROM AcmeWeatherBundle:Endpoint e ORDER BY e.serviceName ASC')
            ->getResult();
    }
}
